# Generated by Django 3.0.2 on 2020-03-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('location_type', models.CharField(max_length=200)),
                ('location_string', models.CharField(max_length=200)),
            ],
        ),
    ]
